<?php
// $Id: stormattribute.module,v 1.4.4.12 2009/07/15 17:45:36 magnity Exp $

/**
 * @file
 */

function stormattribute_help($path, $arg) {
  $output = '';

  switch ($path) {
    case "admin/help#stormattribute":
      $output = '<p>'.  t("Provides attributes support for Storm") .'</p>';
      break;
  }

  return $output;
}


function stormattribute_perm() {
  return array(
    'Storm attribute: access',
    'Storm attribute: add',
    'Storm attribute: edit',
    'Storm attribute: delete',
  );
}


function stormattribute_menu() {
  
  $items['storm/attributes'] = array(
    'title' => t('Attributes'),
    'description' => t('Storm Attributes'),
    'page callback' => 'stormattribute_list',
    'access arguments' => array('Storm attribute: access'),
    'file' => 'stormattribute.admin.inc',
    'type' => MENU_NORMAL_ITEM);
  
  $items['storm/attributes/add'] = array(
    'title' => t('Add a new attribute'),
    'description' => t('Storm Attributes'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stormattribute_add'),
    'access arguments' => array('Storm attribute: add'),
    'file' => 'stormattribute.admin.inc',
    'type' => MENU_CALLBACK);
  
  $items['storm/attributes/edit/%'] = array(
    'title' => t('Edit an attribute'),
    'description' => t('Storm Attributes'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stormattribute_edit', 3),
    'access arguments' => array('Storm attribute: edit'),
    'file' => 'stormattribute.admin.inc',
    'type' => MENU_CALLBACK);
  
  $items['storm/attributes/delete/%'] = array(
    'title' => t('Delete an attribute'),
    'description' => t('Storm Attributes'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('stormattribute_delete', 3),
    'access arguments' => array('Storm attribute: delete'),
    'file' => 'stormattribute.admin.inc',
    'type' => MENU_CALLBACK);
  
  $items['storm/attributes/domain/autocomplete'] = array(
    'title' => t('List of attributes'),
    'description' => t('Storm Attributes'),
    'page callback' => '_stormattribute_domain_autocomplete',
    'page arguments' => array(4),
    'access arguments' => array('Storm attribute: access'),
    'file' => 'stormattribute.admin.inc',
    'type' => MENU_CALLBACK);
  
  return $items;
}


function stormattribute_theme() {
  return array(
    'stormattribute_list' => array(
      'file'      => 'stormattribute.theme.inc',
      'arguments' => array('form'),
    ),
  );
}


function stormattribute_access($op, $item=NULL, $account=NULL) {
  if (empty($account)) {
    global $user;
    $account = $user;
  }

  if ($op == 'create') {
    return user_access('Storm attribute: add');
  }

  if ($op == 'delete') {
    return user_access('Storm attribute: delete');
  }

  if ($op == 'update') {
    return user_access('Storm attribute: edit');
  }
  
  return FALSE;
}


function stormattribute_attributes_bydomain($domain) {
  static $attributes_cache = array();
  $attributes = array();

  if (array_key_exists($domain, $attributes_cache)) return $attributes_cache[$domain];

  $s = "SELECT * FROM {stormattribute} WHERE LOWER(domain) LIKE LOWER('%s') AND isactive=1 ORDER BY weight, avalue";
  $r = db_query($s, $domain);
  $attributes['values'] = array();
  while ($attribute = db_fetch_object($r)) {
    $attributes['values'][$attribute->akey] = t($attribute->avalue);
    if($attribute->isdefault) $attributes['default'] = $attribute->akey;
  }
  if(is_array($attributes['values']) && !array_key_exists('default', $attributes)) {
    $v = array_flip($attributes['values']);
    $attributes['default'] = array_shift($v);
  }

  $attributes_cache[$domain] = $attributes;
  return $attributes;
}


function stormattribute_value($domain, $key) {
  $attributes_array = stormattribute_attributes_bydomain($domain);
  $attributes = $attributes_array['values'];
  if (array_key_exists($key, $attributes)) {
    return $attributes[$key];
  }
  
  return $key;
}
